//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriousGameToolbox.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeriousGameToolbox.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;parameters&gt;
        ///  &lt;parameter type=&quot;integer&quot; id=&quot;TEST_INT&quot; caption=&quot;text_test_int&quot;&gt;
        ///    &lt;values&gt;
        ///      &lt;current&gt;3&lt;/current&gt;
        ///    &lt;/values&gt;
        ///  &lt;/parameter&gt;
        ///
        ///  &lt;parameter type=&quot;float&quot; id=&quot;float&quot; caption=&quot;text_test_int&quot;&gt;
        ///    &lt;values&gt;
        ///      &lt;current&gt;565.584&lt;/current&gt;
        ///    &lt;/values&gt;
        ///  &lt;/parameter&gt;
        ///  
        ///	&lt;parameter type=&quot;range_int&quot; id=&quot;NUMBER_OF_DEFECTS&quot; caption=&quot;text_number_of_situations&quot;&gt;
        ///		&lt;values&gt;
        ///			&lt;min&gt;10&lt;/min&gt;
        ///			&lt;max&gt;40&lt;/max&gt;
        ///			&lt;current&gt;40&lt;/current&gt;
        ///		&lt;/values&gt;
        ///	&lt;/parameter&gt;
        ///
        ///  &lt;parameter ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_settings {
            get {
                return ResourceManager.GetString("default_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;text_container name=&quot;test&quot;&gt;
        ///	&lt;supported_cultures&gt;
        ///		&lt;culture&gt;en&lt;/culture&gt;
        ///		&lt;culture&gt;fr&lt;/culture&gt;
        ///		&lt;culture&gt;invariant&lt;/culture&gt;
        ///	&lt;/supported_cultures&gt;
        ///	&lt;texts&gt;
        ///		&lt;text key=&quot;text 1&quot;&gt;
        ///			&lt;culture name=&quot;invariant&quot; uses=&quot;en&quot;/&gt;
        ///			&lt;culture name=&quot;en&quot;&gt;This is text 1&lt;/culture&gt;
        ///			&lt;culture name=&quot;fr&quot;&gt;Ceci est texte 1&lt;/culture&gt;
        ///		&lt;/text&gt;
        ///	&lt;/texts&gt;
        ///&lt;/text_container&gt;.
        /// </summary>
        internal static string text_container_1 {
            get {
                return ResourceManager.GetString("text_container_1", resourceCulture);
            }
        }
    }
}
